"""
models/recovery_case.py
───────────────────────
The central object in the entire system.

Every failed payout that enters our system becomes a RecoveryCase. Everything
else — agent actions, vendor messages, fund accounts, approvals, audit events —
attaches to a case. The case holds the current state machine state and is the
single source of truth for where a recovery is in its lifecycle.

The case_number is a human-readable identifier (e.g. CASE-000042) used in
the dashboard and in communications, as opposed to the UUID primary key which
is used internally.
"""

import uuid
from datetime import datetime

from sqlalchemy import String, Integer, DateTime, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.enums import CaseState, RecoveryStrategy, RiskLevel


class RecoveryCaseModel(Base):
    __tablename__ = "recovery_cases"

    # ── Primary key ───────────────────────────────────────────────────────────
    id: Mapped[str] = mapped_column(
        String, primary_key=True, default=lambda: str(uuid.uuid4())
    )

    # ── Human-readable case number ────────────────────────────────────────────
    # Generated by the application layer (not the DB) as CASE-XXXXXX
    case_number: Mapped[str] = mapped_column(String, unique=True, nullable=False, index=True)

    # ── Foreign keys ──────────────────────────────────────────────────────────
    # The payout that triggered this case
    payout_id: Mapped[str] = mapped_column(
        String, ForeignKey("payouts.id"), nullable=False
    )

    # The vendor associated with this payout (may be null until the agent looks it up)
    vendor_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("vendors.id"), nullable=True
    )

    # ── Invoice / payment context ─────────────────────────────────────────────
    # The invoice or reference that the payout was for (e.g. INV-2381)
    invoice_reference: Mapped[str | None] = mapped_column(String, nullable=True)

    # Snapshot of the payout amount at case creation (in paise)
    amount: Mapped[int] = mapped_column(Integer, nullable=False)

    # ── Failure details (copied from the payout for quick access) ─────────────
    failure_source: Mapped[str] = mapped_column(String, nullable=False)  # beneficiary_bank, etc.
    failure_reason: Mapped[str] = mapped_column(String, nullable=False)  # invalid_ifsc_code, etc.

    # ── State machine ─────────────────────────────────────────────────────────
    # Current state — the only field the state machine is allowed to change
    state: Mapped[str] = mapped_column(
        String, nullable=False, default=CaseState.CASE_CREATED
    )

    # The recovery strategy chosen by the deterministic classifier
    recovery_strategy: Mapped[str | None] = mapped_column(String, nullable=True)

    # ── Risk and metrics ──────────────────────────────────────────────────────
    risk_level: Mapped[str] = mapped_column(
        String, nullable=False, default=RiskLevel.MEDIUM
    )

    # Total number of agent tool calls made on this case
    action_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Number of times a human had to intervene (approve, reject, review)
    human_intervention_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Updated every time the state changes or agent acts
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Set when the case reaches CASE_RESOLVED, BLOCKED, or ESCALATED
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    payout: Mapped["Payout"] = relationship("Payout", back_populates="recovery_cases")
    vendor: Mapped["Vendor | None"] = relationship("Vendor", back_populates="recovery_cases")
    fund_accounts: Mapped[list["FundAccount"]] = relationship(
        "FundAccount", back_populates="recovery_case"
    )
    messages: Mapped[list["VendorMessage"]] = relationship(
        "VendorMessage", back_populates="case"
    )
    agent_actions: Mapped[list["AgentAction"]] = relationship(
        "AgentAction", back_populates="case"
    )
    approvals: Mapped[list["Approval"]] = relationship(
        "Approval", back_populates="case"
    )
    audit_events: Mapped[list["AuditEvent"]] = relationship(
        "AuditEvent", back_populates="case", order_by="AuditEvent.timestamp"
    )

    def __repr__(self) -> str:
        return (
            f"<RecoveryCase {self.case_number} state={self.state!r} "
            f"amount={self.amount}>"
        )
