"""Phase 1: initial schema

Revision ID: ee2dbb7a0c2f
Revises: 
Create Date: 2026-09-04 05:59:25.148966+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Revision identifiers used by Alembic
revision: str = 'ee2dbb7a0c2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razorpay_payout_id', sa.String(), nullable=False),
    sa.Column('razorpay_fund_account_id', sa.String(), nullable=False),
    sa.Column('razorpay_contact_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_source', sa.String(), nullable=True),
    sa.Column('status_reason', sa.String(), nullable=True),
    sa.Column('status_description', sa.String(), nullable=True),
    sa.Column('razorpay_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_razorpay_payout_id'), 'payouts', ['razorpay_payout_id'], unique=True)
    op.create_index(op.f('ix_payouts_reference_id'), 'payouts', ['reference_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razorpay_contact_id', sa.String(), nullable=True),
    sa.Column('zoho_vendor_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_razorpay_contact_id'), 'vendors', ['razorpay_contact_id'], unique=False)
    op.create_index(op.f('ix_vendors_zoho_vendor_id'), 'vendors', ['zoho_vendor_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('payout_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('invoice_reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('failure_source', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('recovery_strategy', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('human_intervention_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_case_number'), 'recovery_cases', ['case_number'], unique=True)
    op.create_table('agent_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('policy_level', sa.Integer(), nullable=False),
    sa.Column('policy_decision', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_case_id'), 'agent_actions', ['case_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action_description', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('output_hash', sa.String(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('fund_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razorpay_fund_account_id', sa.String(), nullable=False),
    sa.Column('razorpay_contact_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('recovery_case_id', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number_masked', sa.String(), nullable=True),
    sa.Column('ifsc', sa.String(), nullable=True),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('validated_name', sa.String(), nullable=True),
    sa.Column('name_match_score', sa.Integer(), nullable=True),
    sa.Column('is_simulated_validation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_accounts_razorpay_fund_account_id'), 'fund_accounts', ['razorpay_fund_account_id'], unique=True)
    op.create_table('vendor_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_messages_case_id'), 'vendor_messages', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_messages_case_id'), table_name='vendor_messages')
    op.drop_table('vendor_messages')
    op.drop_index(op.f('ix_fund_accounts_razorpay_fund_account_id'), table_name='fund_accounts')
    op.drop_table('fund_accounts')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_case_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_actions_case_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_recovery_cases_case_number'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_vendors_zoho_vendor_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_razorpay_contact_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_payouts_reference_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_razorpay_payout_id'), table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###
